/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#ifndef LED_H
#define LED_H

#include <stdint.h>  					// for uint8_t

void initialise_leds(void);
void set_led_state(uint8_t state);
uint8_t get_led_state(void);
void toggle_leds(void);

#endif
